### ISSUE TITLE
One or more items failed to play. Check the log for more information about this message.

### ISSUE THREAD

**Issue by mikabak** [JupiterBroadcasting/plugin.video.jupiterbroadcasting#66] opened 2016-10-23 07:27 UTC
Very often when using this plugin I get this message.

The log says this:
09:04:09 776899.187500 T:1953288192  NOTICE: DVDPlayer: Opening: http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/techsnap/2016/techsnap-0289-432p.mp4
09:04:09 776899.187500 T:1953288192 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
09:04:09 776899.187500 T:1728566192  NOTICE: Creating InputStream
09:04:11 776901.437500 T:1728566192  NOTICE: Creating Demuxer
09:04:41 776931.562500 T:1728566192   ERROR: Open - Error, could not open file http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/techsnap/2016/techsnap-0289-432p.mp4
09:04:41 776931.562500 T:1728566192   ERROR: OpenDemuxStream - Error creating demuxer
09:04:41 776931.562500 T:1728566192  NOTICE: CDVDPlayer::OnExit()
09:04:41 776931.625000 T:1953288192   ERROR: Playlist Player: skipping unplayable item: 0, path [http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/techsnap/2016/techsnap-0289-432p.mp4]
09:04:41 776931.625000 T:1953288192  NOTICE: CDVDPlayer::CloseFile()
09:04:41 776931.625000 T:1953288192  NOTICE: DVDPlayer: waiting for threads to exit
09:04:41 776931.625000 T:1953288192  NOTICE: DVDPlayer: finished waiting
09:04:41 776931.625000 T:1953288192  NOTICE: CDVDPlayer::CloseFile()
09:04:41 776931.625000 T:1953288192  NOTICE: DVDPlayer: waiting for threads to exit
09:04:41 776931.625000 T:1953288192  NOTICE: DVDPlayer: finished waiting
09:04:41 776931.625000 T:1736954800  NOTICE: Stream All The Sources: Service: Playback Stopped

When I try to download the mp4 on my computer with wget it works fine.
This is the only plugin I have had this problem. That is why I post it here.

I run kodi on a raspberry pi 2 (xbian). My computer and my raspberry pi share the same internet connection.

What can be wrong?
TIA,
Mikael

**Comment by rickyphewitt** [comment] 2016-10-23 13:59
Hello Mikael,

Hmm, I havn't used Xbian in a while. I do have a few questions that might help better understand what is happening:
- What version of Kodi is running on your build of Xbian?
- What version of xbian? 
- Raspberry pi 2 B or just the 2? 
- Are you able to consistently reproduce this, or does it appear to be random?
- Does this happen with all shows, or is it most common on Techsnap?
- If you try to play the show multiple times does it eventually work, or does it always fail?
- Have you been able to play a show that failed previously? If so under what circumstances
- Do you have other video addons that fail in the same way?

Sorry for all the questions, but want to try and narrow this issue down :)

**Comment by mikabak** [comment] 2016-10-26 18:34
Hi,

The version of Kodi is 16.1 Git:2016-05-28-6f8e95d
Operating system: Xbian 1.0 (knockout) (kerel: Linux 4.4.26+)
The raspberry pi box says Raspberry Pi 2 model B.
I have been able to play videos from Jupiter Broadcasing before. I have had occational problems. Nothing consistent. I have the feeling it has gotten worse lately. The last coupple of times I tried I have not been able to play any content from JB. It's not only Technap. I tried LAS and BSD Now. Same problem.
In the past I have been successful in trying to play multiple times, and sometimes the video starts to play. Today I wasn't lycky. Nothing plays no matter how many times I try to play either the same video over and over or try another one. Same issue. In the past I have been able to play a show that previously failed. 
I also have TED talks plugin installed and I have never had any issue playing content with that plugin.

I'm in Europe. Perhaps some issue with the CDN here? On the other hand I am able to play the shows from my computer visiting jupiterboadcasting.com in the browser.

I like kodi and I am a big fan of JB, so I would be very happy if I could get this plugin working again :-)

As a side note: Xbian is som kind of a rolling release and it's auto updating stuff in the background to keep thing uptodate. This is probably good, but can also lead to problems.

Thanks for a nice plugin and a great thank you for trying to help me!
Mikael

**Comment by Xmetalfanx** [comment] 2016-10-26 18:49
Cant say I have experience with Xbian and kodi ... though kodi wise that seems like a recent version ... I am a user of LibreElec on my pi2 here ... and formerly OpenElec (what LibreElec is forked from) .... I wonder what version of the JB addon is being used. 

I know when i upgraded to a beta build of LibreElec based on Kodi 17 my (just an example here) Pandora addon broke .... when i did a fresh install of the latest LibreElec (still based on kodi 16) the addon worked perfectly again

**Comment by rickyphewitt** [comment] 2016-10-27 13:28
Good point @Xmetalfanx with it being rolling its possible that some of the api's used aren't compatible. However that being the case I would expect it to be consistently broken.

@mikabak,
I will do some testing with Xbian this weekend. I have an extra SD card and a RPi 2B. I suspect it might be network issue/script timeout issue, as the url is correct in the debug log and I can load the video in my browser as well. Either way I'll investigate.

**Comment by mikabak** [comment] 2016-10-30 10:32
Today I tried the latest episode of BSDNow with the following results:

11:20:36 317226.093750 T:1925182384  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
11:20:39 317228.687500 T:1534063536 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
11:20:39 317228.750000 T:1953562624  NOTICE: DVDPlayer: Opening: http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/bsdnow/2016/bsd-0165-432p.mp4
11:20:39 317228.781250 T:1953562624 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
11:20:39 317228.781250 T:1559229360  NOTICE: Creating InputStream
11:20:42 317232.093750 T:1534063536 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
11:20:42 317232.093750 T:1534063536  NOTICE: LoadJpeg: unable to load http://www.jupiterbroadcasting.com/wp-content/uploads/2016/10/bsd-0165-v.jpg
11:20:48 317237.375000 T:1559229360  NOTICE: Creating Demuxer
11:21:19 317268.687500 T:1559229360   ERROR: Open - Error, could not open file http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/bsdnow/2016/bsd-0165-432p.mp4
11:21:19 317268.687500 T:1559229360   ERROR: OpenDemuxStream - Error creating demuxer
11:21:19 317268.687500 T:1559229360  NOTICE: CDVDPlayer::OnExit()
11:21:21 317270.375000 T:1953562624   ERROR: Playlist Player: skipping unplayable item: 0, path [http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/bsdnow/2016/bsd-0165-432p.mp4]
11:21:21 317270.375000 T:1953562624  NOTICE: CDVDPlayer::CloseFile()
11:21:21 317270.375000 T:1953562624  NOTICE: DVDPlayer: waiting for threads to exit
11:21:21 317270.375000 T:1953562624  NOTICE: DVDPlayer: finished waiting
11:21:21 317270.375000 T:1953562624  NOTICE: CDVDPlayer::CloseFile()
11:21:21 317270.375000 T:1953562624  NOTICE: DVDPlayer: waiting for threads to exit
11:21:21 317270.375000 T:1953562624  NOTICE: DVDPlayer: finished waiting
11:21:21 317270.468750 T:1745519536  NOTICE: Stream All The Sources: Service: Playback Stopped

As a matter of fact I have nothing against using something other than xbian. If you guys have any other suggestion what I could use to watch JB content, I would be happy to try it. I don't really use many plugins. JB is the most important :-) It would be nice to have a kodi distro that is based on something "standard" (like debian or similar), so I can easily install other software on the raspberry pi as well.

Thanks again for taking the time to help me!
Mikael

**Comment by rickyphewitt** [comment] 2016-10-30 18:16
Thanks for the additional logs! Still shows the same unable to open file with correct links. It also appears to not be able to open the jpg image for that episode either.

Unfortunately my dog seems to have ate my only usb to micro sd reader so I can't flash my pi to xbian right now. Going to order one from Amazon so should be here soon.

@Xmetalfanx and I havn't had issues (that I know of) with OpenElec/LibreElec, if you are not tied to Xbian give those a try.
Open/Libre elec is just a dedicated Kodi applicance so you still wouldn't be able to install deb packages via apt-get. 

When I get the converter I'll throw Xbian on to check for any potential bugs. 

If you do try another distro on the pi let me know how it goes.

Sorry I can't help test sooner.

**Comment by Xmetalfanx** [comment] 2016-10-30 19:33
I have an extra sd card atm (though i should have two ...  one was faulty ... seller gave me $ back ... anyway i am getting sidetracked) ... going to give Xbian a look

**Comment by Xmetalfanx** [comment] 2016-10-30 19:41
I tried those exact shows you had in the log and they (i had to fix the resolution on my fresh Xbian install) play fine ... I will not lie ... this looks like it has interesting additions to Kodi I dont see on the *Elecs ... I MAY keep this, WHILE stillhaving another SD card with LibreELec

**Comment by mikabak** [comment] 2016-11-20 13:00
I installed latest LibreElec. It has Kodi 16.1. The only plugin installed so far is JB. So far the videos play fine. Perhaps a fresh install was all needed to get this work.
Thanks for a great plugin!

**Comment by rickyphewitt** [comment] 2016-11-20 15:10
@mikabak,

Thanks for the update. I've had weird issues over time as cruft built up on my kodi boxes, sometimes a clean install is the only cure :). 

 I''ll keep this open for another week and if you don't have any issues by then we can close it.

**Comment by RobLoach** [comment] 2016-11-20 16:34
Ran through some of the different live feeds on LibreELEC `master`, and it seemed to work okay. Did take a while to load the different RSS feeds though. Likely slow wifi.

May be a good idea to implement some kind of caching layer.

**Closed as completed** 2016-11-30 01:00 UTC
Labels: Support

**Comment by mikabak** [comment] 2017-01-23 16:07
Unfortunately I seem to have problems again:

16:55:49 480.994293 T:1962512384  NOTICE: DVDPlayer: Opening: http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep453-432p.mp4
16:55:49 480.994598 T:1962512384 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:55:49 480.997162 T:1614803872  NOTICE: Creating InputStream
16:55:57 489.470459 T:1614803872  NOTICE: Creating Demuxer
16:56:27 519.574890 T:1614803872   ERROR: Open - Error, could not open file http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep453-432p.mp4
16:56:27 519.575195 T:1614803872   ERROR: OpenDemuxStream - Error creating demuxer
16:56:27 519.575317 T:1614803872  NOTICE: CDVDPlayer::OnExit()
16:56:27 519.579773 T:1962512384   ERROR: Playlist Player: skipping unplayable item: 0, path [http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep453-432p.mp4]
16:56:27 519.580566 T:1962512384  NOTICE: CDVDPlayer::CloseFile()
16:56:27 519.580750 T:1962512384  NOTICE: DVDPlayer: waiting for threads to exit
16:56:27 519.580872 T:1962512384  NOTICE: DVDPlayer: finished waiting
16:56:27 519.580994 T:1962512384  NOTICE: CDVDPlayer::CloseFile()
16:56:27 519.581055 T:1962512384  NOTICE: DVDPlayer: waiting for threads to exit
16:56:27 519.581177 T:1962512384  NOTICE: DVDPlayer: finished waiting

The stream doesn't even start.
I have LibreElec 7.0.3 with Kodi 16.1.

@RobLoach  as for caching layer you can do that with Kodi in advanced settings. Here is mine:
`
<advancedsettings>
<network>
<curlclienttimeout>30</curlclienttimeout>
<curlretries>2</curlretries>
<curllowspeedtime>20</curllowspeedtime>
<buffermode>1</buffermode>
<cachemembuffersize>104857600</cachemembuffersize>
<readbufferfactor>1.5</readbufferfactor>
</network>
</advancedsettings>
`

The curlclienttimeout is set pretty high because I thought a higher value would let me play the JB streams. I even set the JB plugin to play the low quality stream. It doesn't help.

Maybe I should ask Mr. Jude if the CDN for Central Europe is working ok.

**Comment by rickyphewitt** [comment] 2017-01-29 13:54
@mikabak,

The plugin code hasn't changed since October so I suspect its network related. We do have a feature in for caching, however currently its only the feeds and not the actual episodes. The log shows you can access the episode listing, but the video does not play.
I have not messed with the curl client timeout settings in my own install of kodi, might try bumping them up a bit more to allow more time before kodi times out.

**Comment by Drasky** [comment] 2017-02-07 00:51
Having the exact same problem on a Raspberry Pi 3 with Kodi 16.1. Log says:

16:13:41 12651.458008 T:1786409904 WARNING: Attempt to use invalid handle 2
16:13:52 12663.180664 T:1751020464   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://www.jupiterbroadcasting.com/wp-content/uploads/2017/02/las455-v.jpg
16:13:58 12669.073242 T:1943654400   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep455.mp4
16:13:58 12669.141602 T:1943654400  NOTICE: DVDPlayer: Opening: http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep455.mp4
16:13:58 12669.141602 T:1943654400 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:13:58 12669.145508 T:1778021296  NOTICE: Creating InputStream
16:14:09 12679.666016 T:1778021296   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep455.mp4
16:14:19 12689.687500 T:1778021296   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
16:14:19 12689.688477 T:1778021296   ERROR: CCurlFile::Open failed with code 0 for http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep455.mp4
16:14:19 12689.688477 T:1778021296   ERROR: Open - failed to open source <http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep455.mp4>
16:14:19 12689.688477 T:1778021296   ERROR: CDVDPlayer::OpenInputStream - error opening [http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep455.mp4]
16:14:19 12689.688477 T:1778021296  NOTICE: CDVDPlayer::OnExit()
16:14:19 12689.689453 T:1943654400   ERROR: Playlist Player: skipping unplayable item: 0, path [http://www.podtrac.com/pts/redirect.mp4/201406.jb-dl.cdn.scaleengine.net/las/2017/linuxactionshowep455.mp4]
16:14:19 12689.703125 T:1943654400  NOTICE: CDVDPlayer::CloseFile()

advancedsettings.xml contains:

&lt;advancedsettings&gt;
&lt;playlisttimeout&gt;20&lt;/playlisttimeout&gt;
&lt;network&gt;
&lt;curlclienttimeout&gt;10&lt;/curlclienttimeout&gt;
&lt;curllowspeedtime&gt;20&lt;/curllowspeedtime&gt;
&lt;curlretries&gt;2&lt;/curlretries&gt;
&lt;buffermode&gt;1&lt;/buffermode&gt;
&lt;cachemembuffersize&gt;20971520&lt;/cachemembuffersize&gt;
&lt;readbufferfactor&gt;4.0&lt;/readbufferfactor&gt;
&lt;/network&gt;
&lt;/advancedsettings&gt;

**Comment by Drasky** [comment] 2017-02-07 01:13
I have no problem using the plugin from kodi on my laptop, and opening those URL's in the webbrowser on the Pi works fine. I'm wondering if there is something strange they are doing with the redirect that curl on the Pi doesn't like.

**Comment by rickyphewitt** [comment] 2017-02-07 01:27
@Drasky,

Are you using an embedded distro like Libre/Open ELEC? on the pi? Also It doesn't look like you were able to open the show images either. Where as @mikabak just had issues with the show itself.

@Drasky, @mikabak,

Both of you have added AdvancedSettings.xml to your kodi config with explicit settings for the curl client timeout. Was this added to resolve the JB plugin timeout or were other plugins also experiencing timeout issues?

I have not experienced this with my PI2 (OpenElec) and I do not have any custom AdvancedSettings
